# Config override for deployment
version: '3'

services:
  backend:
    volumes:
    - ./keys:/private:ro
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=8080"
    - "traefik.frontend.rule=Host:codymaze.wom.social"
    - "traefik.frontend.entryPoints=http,https"
    - "traefik.frontend.redirect.entryPoint=https"
    restart: unless-stopped
