# Config override for deployment
version: '3'

services:
  backend:
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:codymaze.wom.social"
    - "traefik.frontend.entryPoints=http,https"
    - "traefik.frontend.redirect.entryPoint=https"
