version: '3'

networks:
  web:
    external: true

services:
  backend:
    build: ./src/Backend
    networks:
    - web
    expose:
    - "80"
    env_file:
    - config.env
    volumes:
    - ./keys:/keys:ro
