name: mirabilandia
description: WOM processor for CodyMaze.
version: 0.1.0
author: Gian Marco Di Francesco

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  uuid:
  shelf: ^1.2.0
  shelf_router: ^1.1.1
  dart_wom_connector: 0.0.2-nullsafety.3
